name: decision-transformer-gym
channels:
- pytorch
dependencies:
- python=3.8.5
- anaconda
- cudatoolkit=10.
- numpy
- pip
- pip:
  - gym==0.18.3
  - mujoco
  - numpy==1.20.3
  - torch==1.8.1
  - transformers==4.5.1
  - wandb==0.13.4
  - hydra-core==1.2.0
  - tqdm
